import type { PortfolioItem } from '#lib/types.ts';

/** Repository-backed portfolio content, independent of the contact database. */
export const portfolioItems: PortfolioItem[] = [
  {
    id: 1,
    title: 'Forewit',
    description:
      'Engineering software for people and AI agents. Starting with MEP tools that replace scattered Excel workflows with shared project data and agent-usable calculation logic.',
    image_url: '',
    project_url: 'https://surfside-software.com',
    github_url: '',
    technologies: [
      'TypeScript',
      'TanStack Start',
      'Effect',
      'Cloudflare Workers',
      'D1',
      'MCP',
    ],
    featured: true,
    highlighted: true,
    display_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    title: 'Intelligent Irrigation',
    description:
      'Irrigation design software for Corexis that generates more efficient designs to save water and money.',
    image_url: '',
    project_url: '',
    github_url: '',
    technologies: [
      'Ruby on Rails',
      'PostgreSQL',
      'PostGIS',
      'Python',
      'EPANET',
      'Stimulus',
    ],
    featured: true,
    display_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    title: 'Permit Monitor',
    description:
      'Local desktop app for Windows and macOS that tracks public building permits across Florida counties, cities, and water management districts, with Jev, a decisions/system model, built in.',
    image_url: '',
    project_url: '',
    github_url: '',
    technologies: ['Electron', 'TypeScript', 'Playwright', 'Zod'],
    featured: true,
    display_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 4,
    title: 'Moke Agent',
    description:
      'AI-powered AEC drawing QC review pipeline. Locates project drawings, splits PDFs by engineering discipline, runs discipline-specific AI review with Synthetic AI / Kimi K2.5 and an OpenRouter fallback, and generates formatted review reports.',
    image_url: '',
    project_url: '',
    github_url: '',
    technologies: [
      'TypeScript',
      'Bun',
      'Effect-TS',
      'OpenRouter AI',
      'Zod',
      'pdf-lib',
    ],
    featured: true,
    display_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 5,
    title: 'AEC Project Lighthouse',
    description:
      'Project management SaaS for architecture, engineering, and construction teams. Features real-time collaboration, Gantt charts, markdown editing, email notifications, and automated tests. Live at aeccloud.io.',
    image_url: '',
    project_url: 'https://www.aeccloud.io',
    github_url: '',
    technologies: [
      'React 19',
      'TypeScript',
      'Convex',
      'Vite',
      'Tailwind CSS',
      'Vitest',
      'Playwright',
    ],
    featured: true,
    display_order: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 6,
    title: 'General AI Tooling for AEC Engineers',
    description:
      'A kit for using general-purpose AI in architecture, engineering, and construction work. It combines reusable agent skills, repeatable workflows, executable Python workbooks, and feedback loops that turn one-off experiments into repeatable engineering processes.',
    image_url: '',
    project_url: '',
    github_url: '',
    technologies: [
      'Agent Skills',
      'Reusable Workflows',
      'Python Workbooks',
      'Feedback Loops',
    ],
    featured: true,
    display_order: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 7,
    title: 'Moke Script',
    description:
      'AI-powered planset review and comparison tool for construction drawings. Ships as a desktop CLI for Windows, macOS, and Linux that reviews or diffs PDF plansets into an HTML report, plus a hosted SvelteKit web app on Cloudflare with review jobs, auth, and D1/R2 storage.',
    image_url: '',
    project_url: '',
    github_url: '',
    technologies: [
      'SvelteKit',
      'TypeScript',
      'Cloudflare Workers',
      'D1',
      'R2',
      'Codex CLI',
      'pdf-to-img',
    ],
    featured: true,
    display_order: 7,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 8,
    title: 'ScoutWork',
    description:
      'AI-powered job search and recruiting platform with chat-based matching and a dark "Night Desk" theme. Aggregates listings via SerpApi, runs chat on Cloudflare Workers AI, stores data in D1 with résumé uploads in R2, and gates access with magic-link email auth.',
    image_url: '',
    project_url: '',
    github_url: '',
    technologies: [
      'TanStack Start',
      'React',
      'TypeScript',
      'Cloudflare Workers',
      'D1',
      'R2',
      'Workers AI',
      'SerpApi',
    ],
    featured: true,
    display_order: 8,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 9,
    title: 'BricsCAD / AutoCAD MCP Server',
    description:
      'Code-mode MCP integration for AI-assisted drafting in BricsCAD alongside an isolated AutoCAD connector. A Python stdio server attaches to the running CAD session over Windows COM, serializes spool jobs, executes generated PyRx code inside BricsCAD, and returns structured results with transaction rollback.',
    image_url: '',
    project_url: '',
    github_url: '',
    technologies: ['Python 3.12', 'FastMCP', 'PyRx', 'Windows COM', 'JSON-RPC'],
    featured: true,
    display_order: 9,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 10,
    title: 'Snip-it',
    description:
      'Chrome Manifest V3 extension for capturing excerpts from building, fire, and electrical codes during code research. Clips and organizes citations, indexes them with fuzzy search, and syncs to Dropbox so references can be re-found later.',
    image_url: '',
    project_url: '',
    github_url: '',
    technologies: [
      'WXT',
      'Svelte 5',
      'TypeScript',
      'MiniSearch',
      'Dexie',
      'Dropbox SDK',
    ],
    featured: false,
    display_order: 10,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 11,
    title: 'Link Converter Utilities',
    description:
      'Two web services that convert shared links. One rewrites Apple Maps links in incoming SMS/RCS messages to Google Maps links. The other converts Apple Music links to Spotify using the Odesli API with a Spotify search fallback.',
    image_url: '',
    project_url: '',
    github_url: '',
    technologies: [
      'Go',
      'TypeScript',
      'React 19',
      'SQLite',
      'Spotify API',
      'Docker',
    ],
    featured: false,
    display_order: 11,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
