-- Portfolio Items
INSERT INTO portfolio_items (title, description, image_url, project_url, github_url, technologies, featured, display_order) VALUES
-- Featured
('Moke Agent', 'AI-powered AEC drawing QC review pipeline. Automatically locates project drawings, splits PDFs by engineering discipline, runs discipline-specific AI review (Synthetic AI / Kimi K2.5 with an OpenRouter fallback), and generates formatted review reports.', NULL, NULL, NULL, '["TypeScript", "Bun", "Effect-TS", "OpenRouter AI", "Zod", "pdf-lib"]', 1, 1),
('AEC Project Lighthouse', 'Full-featured project management SaaS for architecture, engineering, and construction teams. Real-time collaboration, Gantt charts, markdown editing, email notifications, and comprehensive test coverage. Live at aeccloud.io.', NULL, 'https://www.aeccloud.io', NULL, '["React 19", "TypeScript", "Convex", "Vite", "Tailwind CSS", "Vitest", "Playwright"]', 1, 2),
('Echocaster', 'Document-to-podcast generator that turns uploaded text into narrated audio episodes. A TanStack web client pairs with a Cloudflare Workers API that ingests documents, orchestrates background text-to-speech jobs through Cloudflare Queues, assembles multi-chunk audio, and streams playable episodes with per-episode playback state.', NULL, NULL, NULL, '["TanStack Start", "React", "TypeScript", "Hono", "Cloudflare Workers", "D1", "R2", "Cloudflare Queues", "Workers AI"]', 1, 3),
('Sheaf', 'Cross-platform Markdown note-taking app built for fast, formatted-writing-first capture with multi-device sync and note-level sharing (Viewer/Editor). Runs entirely on Cloudflare primitives — Workers, D1, and a Durable Object for coordination — with web and Android clients, offline-capable sync, and self-hostable open infrastructure.', NULL, NULL, NULL, '["SvelteKit", "Svelte 5", "TypeScript", "Cloudflare Workers", "D1", "Durable Objects", "Better Auth"]', 1, 4),
('Moke Script', 'AI-powered planset review and comparison tool for construction drawings. Ships as a cross-platform desktop CLI (Windows/macOS/Linux) that reviews or diffs PDF plansets into an HTML report, plus a hosted SvelteKit web app on Cloudflare with review jobs, auth, and D1/R2 storage.', NULL, NULL, NULL, '["SvelteKit", "TypeScript", "Cloudflare Workers", "D1", "R2", "Codex CLI", "pdf-to-img"]', 1, 5),
('Kalshi Sniper Bot', 'Algorithmic trading bot that snipes Kalshi binary event contracts in the final 10–60 seconds before expiration, targeting outcomes that are near-certain but not yet priced in. Features a supervised Effect-TS runtime with SQLite (WAL) persistence, WebSocket market data with gap repair, startup reconciliation, and a ledger-derived accounting system.', NULL, NULL, NULL, '["TypeScript", "Bun", "Effect-TS", "WebSocket", "SQLite"]', 1, 6),
('ScoutWork', 'AI-powered job search and recruiting platform with intelligent search and conversational matching, wrapped in a warm "Night Desk" dark aesthetic. Aggregates listings via SerpApi, runs chat on Cloudflare Workers AI, stores data in D1 with résumé uploads in R2, and gates access with magic-link email auth.', NULL, NULL, NULL, '["TanStack Start", "React", "TypeScript", "Cloudflare Workers", "D1", "R2", "Workers AI", "SerpApi"]', 1, 7),
('BricsCAD MCP Server', 'MCP server that gives AI assistants COM-based access to BricsCAD drafting operations. Supports drawing lines, circles, arcs, polylines, and rectangles, opening DWG files, and publishing layouts to PDF.', NULL, NULL, NULL, '["Go", "MCP SDK", "COM Automation", "BricsCAD API"]', 1, 8),
('AEC Property Hunter', 'Internal property research workspace for parcel review, zoning context collection, AI-assisted viability analysis, and PDF report generation. Supports multi-county parcel data seeding.', NULL, NULL, NULL, '["React 19", "TanStack Start", "Drizzle ORM", "Turso", "OpenRouter AI", "Jina AI", "Tailwind CSS"]', 1, 9),
-- Project Index
('AEC Agent Consensus', 'Chat interface that queries several LLMs in parallel and reconciles their answers into a single consensus response, so engineers get a cross-checked answer instead of trusting any one model. Built on a fast Bun + React stack.', NULL, NULL, NULL, '["Bun", "React", "TypeScript", "Tailwind CSS", "shadcn/ui"]', 0, 10),
('CardStore', 'Full-stack sports card e-commerce store with a public catalog, cart, and Stripe checkout, plus an admin dashboard for inventory management, CSV import, image galleries, and sales charts. Built on TanStack Start and Cloudflare.', NULL, NULL, NULL, '["TanStack Start", "React", "TypeScript", "Cloudflare Workers", "Drizzle ORM", "Better Auth", "Stripe", "Resend", "Tailwind CSS"]', 0, 11),
('Snip-it', 'Chrome (Manifest V3) extension for capturing excerpts from building, fire, and electrical codes during code research. Clips and organizes citations, indexes them with fuzzy search, and syncs to Dropbox so references can be re-found later.', NULL, NULL, NULL, '["WXT", "Svelte 5", "TypeScript", "MiniSearch", "Dexie", "Dropbox SDK"]', 0, 12),
('CafeFit', 'Fitness tracking Progressive Web App for calorie tracking, weight management, and workout logging with offline support. Built with TanStack Start on Cloudflare Workers with a D1 SQLite database.', NULL, 'https://cafefit.xyz', NULL, '["TanStack Start", "React 19", "TypeScript", "Drizzle ORM", "Cloudflare D1", "Better Auth", "Tailwind CSS v4", "Chart.js", "PWA"]', 0, 13),
('Apple Maps to Google Maps Converter', 'Web service that automatically converts Apple Maps links in incoming SMS/RCS messages to Google Maps links. Features encrypted key storage, rate limiting, audit logging, and idempotency tracking.', NULL, NULL, NULL, '["Go", "TypeScript", "React 19", "SQLite", "Docker"]', 0, 14),
('Apple Music to Spotify', 'Web service that converts Apple Music links to Spotify equivalents using the Odesli API as the primary resolver with a Spotify search fallback. Caches results in SQLite.', NULL, NULL, NULL, '["Go", "TypeScript", "React 19", "SQLite", "Spotify API", "Docker"]', 0, 15),
('Accredited Home Repair', 'Marketing site for a home-repair contractor with service pages and programmatically generated per-city service-area landing pages for local SEO. Built with SvelteKit and backed by Cloudflare D1 via Drizzle.', NULL, NULL, NULL, '["SvelteKit", "Svelte 5", "TypeScript", "Drizzle ORM", "Cloudflare D1", "Tailwind CSS"]', 0, 16),
('LightSpeed Music', 'High-performance artist website with an interactive starfield/warp-speed canvas animation, Spotify player embeds, and links to all major streaming platforms.', NULL, NULL, NULL, '["Next.js 15", "React 19", "TypeScript", "Tailwind CSS", "Canvas API"]', 0, 17),
('Advanced Website', 'Ground-up redesign and reimplementation of the original WordPress site for Advanced Engineering Consultants. Re-architected with Laravel and React (Inertia.js) including service pages, gallery, contact forms, and a careers portal; currently in development.', NULL, NULL, NULL, '["Laravel", "React 19", "Inertia.js", "TypeScript", "Tailwind CSS", "PHP 8"]', 0, 18),
('BlueForge', 'Custom immutable Linux desktop OS image built on Universal Blue''s Bluefin. A multi-stage Containerfile bakes in a Ghostty-first terminal, security tooling (1Password, Mullvad), and a curated Homebrew/Flatpak app set for a reproducible daily-driver dev environment.', NULL, NULL, 'https://github.com/sc-frederick/BlueForge', '["Containerfile", "Bash", "Just", "Universal Blue", "Homebrew", "Flatpak", "Podman"]', 0, 19),
('AEC Marketing Skills', 'Library of agent skill packages and CLI scripts that automate internal AEC marketing operations — local SEO, Google Business Profile management, keyword research, content drafting, and social planning — as markdown skills plus Bun/TypeScript tooling.', NULL, NULL, NULL, '["Bun", "TypeScript", "Markdown", "OpenCode", "GA4 / GSC"]', 0, 20),
('GeoAddressMap LSP', 'BricsCAD AutoLISP routine that geocodes street addresses via OpenStreetMap Nominatim and sets the drawing''s geographic location with the FL83-WF coordinate system.', NULL, NULL, NULL, '["AutoLISP", "Nominatim API", "ESRI ArcGIS", "BricsCAD"]', 0, 21),
('TEXTALLCAPS', 'BricsCAD AutoLISP plugin that automatically converts TEXT, MTEXT, and MULTILEADER content to uppercase using command and database reactors.', NULL, NULL, NULL, '["AutoLISP", "VLR Reactors", "COM Automation", "BricsCAD"]', 0, 22),
('Civil Perplexity Space', 'Knowledge base and conversation analysis tool for civil engineering with curated AI system instructions for Florida codes, standards, stormwater, and materials.', NULL, NULL, NULL, '["Python", "JSON", "HTML", "Florida Building Codes"]', 0, 23);

-- Sample Blog Posts
INSERT INTO blog_posts (title, slug, content, excerpt, cover_image, tags, published, published_at) VALUES
('Getting Started with React Server Components', 'getting-started-react-server-components', 
'<h1>Getting Started with React Server Components</h1><p>React Server Components represent a paradigm shift in how we build React applications...</p><h2>What are Server Components?</h2><p>Server Components allow you to render components on the server, reducing the JavaScript bundle size sent to the client...</p><h2>Benefits</h2><ul><li>Reduced bundle size</li><li>Direct backend access</li><li>Improved performance</li></ul>', 
'Learn how to leverage React Server Components to build faster, more efficient React applications with reduced client-side JavaScript.', 
'https://example.com/blog/server-components.jpg', '["React", "JavaScript", "Performance"]', 1, '2024-03-15 10:00:00'),

('Modern CSS Architecture with Tailwind', 'modern-css-architecture-tailwind',
'<h1>Modern CSS Architecture with Tailwind</h1><p>Tailwind CSS has revolutionized how we approach styling in web applications...</p><h2>Utility-First Approach</h2><p>The utility-first methodology changes how we think about CSS...</p>',
'Discover best practices for organizing and scaling your Tailwind CSS codebase in large applications.',
'https://example.com/blog/tailwind-architecture.jpg', '["CSS", "Tailwind", "Architecture"]', 1, '2024-02-28 14:30:00'),

('Building Resilient APIs with TypeScript', 'building-resilient-apis-typescript',
'<h1>Building Resilient APIs with TypeScript</h1><p>Type safety is crucial for building maintainable APIs...</p><h2>Type Safety Benefits</h2><p>Using TypeScript for APIs provides compile-time type checking...</p>',
'Learn how to leverage TypeScript to build type-safe, resilient APIs that scale.',
'https://example.com/blog/typescript-apis.jpg', '["TypeScript", "API", "Node.js"]', 0, NULL);

-- Sample Contact Submissions
INSERT INTO contact_submissions (name, email, subject, message, status, created_at) VALUES
('John Smith', 'john.smith@example.com', 'Project Inquiry', 'Hi Stephen, I came across your portfolio and I am impressed with your work. I have a project that I would like to discuss with you. Can we schedule a call next week?', 'read', '2024-03-10 09:15:00'),
('Sarah Johnson', 'sarah.j@techcorp.com', 'Freelance Opportunity', 'Hello, We are looking for a senior frontend developer for a 6-month contract. Your React and TypeScript experience looks like a great fit. Would you be interested in learning more?', 'pending', '2024-03-14 16:45:00'),
('Michael Chen', 'mchen.dev@example.com', 'Collaboration', 'Hey Stephen, I saw your work on the AI Dashboard project. I am building something similar and would love to compare notes. Are you open to a quick chat?', 'read', '2024-03-12 11:20:00'),
('Alice Williams', 'alice@startup.io', 'Consulting Request', 'We need help optimizing our React application performance. Your blog posts suggest you have expertise in this area. Can we discuss consulting rates?', 'replied', '2024-03-08 13:00:00');

-- Sample Analytics Events
INSERT INTO analytics_events (event_type, page_path, referrer, session_id, metadata, created_at) VALUES
('pageview', '/', 'https://google.com', 'sess_001', '{"device": "desktop", "country": "US"}', '2024-03-15 08:00:00'),
('pageview', '/portfolio', NULL, 'sess_001', '{"device": "desktop", "country": "US"}', '2024-03-15 08:00:15'),
('pageview', '/blog', NULL, 'sess_001', '{"device": "desktop", "country": "US"}', '2024-03-15 08:01:30'),
('click', '/portfolio', NULL, 'sess_001', '{"element": "project-card", "project": "E-Commerce Platform"}', '2024-03-15 08:00:45'),
('pageview', '/', 'https://twitter.com', 'sess_002', '{"device": "mobile", "country": "UK"}', '2024-03-15 09:30:00'),
('pageview', '/contact', NULL, 'sess_002', '{"device": "mobile", "country": "UK"}', '2024-03-15 09:32:00'),
('click', '/contact', NULL, 'sess_002', '{"element": "submit-button"}', '2024-03-15 09:35:00'),
('pageview', '/', NULL, 'sess_003', '{"device": "desktop", "country": "CA"}', '2024-03-15 10:15:00'),
('pageview', '/blog/getting-started-react-server-components', 'https://linkedin.com', 'sess_003', '{"device": "desktop", "country": "CA"}', '2024-03-15 10:16:00'),
('scroll', '/blog/getting-started-react-server-components', NULL, 'sess_003', '{"depth": 75}', '2024-03-15 10:18:00');
